### ISSUE TITLE
Additional palm sign ($) throwing error during installation.

### ISSUE THREAD

**Issue by ahmadfaizan965** [electron/website#110]
I used the **COPY BUTTON** in code section to copy the installation command, it copied
 ``` $ npm install --save-dev electron ```

since the terminal already have the palm sign ($) so it is throwing error that `$ is not a command` it would be better if it the copied text excludes the sign.

thank you.

![electron issue](https://user-images.githubusercontent.com/69793423/135753931-bf5332ae-a09f-484e-8ecc-b343d726a98b.png)

**Comment by erickzhao** [comment]
Thank you for the report! This is definitely something we should look out for.

**Comment by ahmadfaizan965** [comment]
@erickzhao you're welcome :-)

**Comment by hansupadhyay007** [comment]
Hey there..
I really wanted to work on this issue. Could you please assign me this...

**Comment by erickzhao** [comment]
@hansupadhyay007 PRs welcome

**Comment by sudhz** [comment]
I think this issue is fixed now, someone should probably close this.
