### ISSUE TITLE
Revamp get started tutorial

### ISSUE THREAD

**Issue by molant** [electron/website#122]
A consistent feedback we have received from multiple places is that developers have a hard time finding information on our docs. Sometimes it is becacuse that documentation does not exist, others because it is not easily discoverable (how to search for what you don't know?).

The following is a WIP outline of the Quick start guide, so feedback is welcome:

- Introduction
  - Web concepts
  - nodejs installed
  - [Process model](https://www.electronjs.org/docs/latest/tutorial/process-model)
- Scaffolding
  - [Debugging with VS Code](https://www.electronjs.org/docs/latest/tutorial/debugging-vscode) --> Maybe add the configuration to the quick-start?
- Accessing Node.js APIs--> Talk about [Context isolation](https://www.electronjs.org/docs/latest/tutorial/context-isolation) and prerenderer and how to implement things.
  - Link again to [process model](https://www.electronjs.org/docs/latest/tutorial/process-model) or mention things?
  - Use `process.versions` as an example on how to implement, mention that node integration is to be avoided
  - Link to the security docs ([Context isolation](https://www.electronjs.org/docs/latest/tutorial/context-isolation), [Process sandboxing](https://www.electronjs.org/docs/latest/tutorial/sandbox), [Checklist](https://www.electronjs.org/docs/latest/tutorial/security))
- Deeper integration with the OS
  - Have a list of all the other stuff --> Manually for now, but will be good to get something populated automatically that uses the description and other stuff
- [Application distribution](https://www.electronjs.org/docs/latest/tutorial/application-distribution)
  - Link to all the other links under distribution ([Code signing](https://www.electronjs.org/docs/latest/tutorial/code-signing), [Mac App Store Submission Guide](https://www.electronjs.org/docs/latest/tutorial/mac-app-store-submission-guide), [Windows Store Guide](https://www.electronjs.org/docs/latest/tutorial/windows-store-guide), [Snapcraft Guide (Linux)](https://www.electronjs.org/docs/latest/tutorial/snapcraft)
- [Updating Applications](https://www.electronjs.org/docs/latest/tutorial/updates)
- Further reading: Go to Examples and look at the API, [performance](https://www.electronjs.org/docs/latest/tutorial/performance), [fuses](https://www.electronjs.org/docs/latest/tutorial/fuses), etc.?

**Comment by erickzhao** [comment]
I think this is done!
