### ISSUE TITLE
Redesign error 404 page

### ISSUE THREAD

**Issue by khareyash05** [electron/website#194]
Currently the error 404 page looks very simple. I would like to make this page more appealing to the viewers. I will also be adding a link to the home page of the website

**Comment by molant** [comment]
Sure @khareyash05,

What do you have in mind?

**Comment by khareyash05** [comment]
I will be sharing some designs with you

**Comment by Mridul07Sharma** [comment]
@molant can you assign this issue to me, I have an idea with me.

**Comment by molant** [comment]
Feel free to share your designs here. I'll assign when someone is ready to start implementing :)
Thanks!

**Comment by Aryangp** [comment]
i am new to open source. i want to contribute to this issue .can i start on this

**Comment by Frs2304** [comment]
Hi! I want to work on this issue.
@molant  Please assign me this issue to me..
<img width="500" alt="Error404" src="https://user-images.githubusercontent.com/104261490/214591146-1e4c76cf-7320-46f2-b43c-83f08ed261d1.png">
I will make the Error404 page look similar to this..I can also change the image as per electron guidelines.

**Comment by molant** [comment]
Unless @erickzhao has another opinion, I'd say go ahead and do a PR with the changes.

I try to avoid assigning this low hanging PRs to anyone so they can be done by anyone on a First Come - First Merged basis type of thing.

**Comment by erickzhao** [comment]
Yeah, I don't like assigning issues since people tend to ask and just fade away sometimes.

That said, we already have a PR for this but it has stalled due to an enormous git diff that has not been fixed yet: https://github.com/electron/website/pull/257

Happy to accept other PRs in a better state.

**Comment by prashantexe** [comment]
![Screenshot_20230207_221342](https://user-images.githubusercontent.com/111880621/217308634-49e1ae7f-90b8-4a08-b945-95841edf7daf.png)

Hi! @molant I want to work on this issue.

**Comment by molant** [comment]
As @erickzhao [mentioned earlier](https://github.com/electron/website/issues/194#issuecomment-1404152732) to someone else, please go ahead with a PR and if it's in good shape we will merge it 😊

Thank you 🙏
