### ISSUE TITLE
18.3.x changelogs are not generating

### ISSUE THREAD

**Issue by Slapbox** [electron/website#254]
https://www.electronjs.org/releases/stable?version=18

Releases after 18.3.6 are not shown.

**Comment by erickzhao** [comment]
Hey @Slapbox, I'm in the process of deprecating that page but haven't made the transition yet. It should be replaced by:

https://releases.electronjs.org/releases/stable?version=18

**Comment by Slapbox** [comment]
Thanks for your great work @erickzhao! Feel free to close this whenever you deem appropriate.

**Comment by erickzhao** [comment]
The page was entirely replaced! Closing.

**Comment by Slapbox** [comment]
@erickzhao I don't want to make a whole issue for this quality of life thing, but I did want to mention how nice a "First" and "Last" page button would be on the new pages: https://releases.electronjs.org/releases/stable?version=20

You can click "5" at the bottom, but there's still more pages to go, so it can become quite onerous to get to the initial changelog entry for major releases (which are the ones we need to access the most often, by far.)

**Comment by erickzhao** [comment]
I put up a PR for that in the respective repository. Should hopefully land soon!

**Comment by Slapbox** [comment]
@erickzhao thank you so much, I'm so happy to see a "Last" button now!
