### ISSUE TITLE
ambiguity in the description of api/ipcmain.md

### ISSUE THREAD

**Issue by albu77** [electron/website#292]
- The description say:

"_Communicate asynchronously **from the main** process **to renderer processes**._"

- In the ipcMain introduction this become:

"When **used in the main** 
process, it handles asynchronous and synchronous messages sent **from a renderer
process** (web page)."
So to my sense two things are not clear the directions of the communication and the sync/async mode of them. And further there is the assumption it could be used somewhere else than in the main process......

**Comment by Sudhir878786** [comment]
@albu77 

In the first description, it is stating that the main process can communicate asynchronously with renderer processes. This means that the main process can send messages to the renderer processes without having to wait for a response. The renderer processes can then receive and process the messages at their own pace.

In the second description, it is stating that when used in the main process, the IPC (Inter-Process Communication) module handles both asynchronous and synchronous messages sent from a renderer process (web page). This means that the main process can send and receive both types of messages to and from the renderer processes.

Asynchronous messages are sent without waiting for a response, while synchronous messages require a response before continuing.

It is also mentioned that the IPC module can be used somewhere else than in the main process in Electron. This means that the IPC module can be used for communication between different processes within the Electron application, not just between the main process and renderer processes.

**Comment by Sudhir878786** [comment]
Hope you got it @albu77 
Thanks  
Issue #292 closed

**Comment by ckerr** [comment]
If this is still in error, the issue should be opened on `electron/electron` because that repository is where the documentation is stored. The website is just presenting the data that's in e/e
