### ISSUE TITLE
Correction to bring to web-contents.md and webview-tag

### ISSUE THREAD

**Issue by albu77** [electron/website#304]
In <**webview>.printToPDF(options)** and  **contents.printToPDF(options)** (same things in both files) :
Hum Sound strange for the margins to be set in inches and said default to cm....
margin in inches. Defaults to 1cm (~0.4 inches).
And a little bit further:
pageRanges string (optional) - **_Paper_** ranges to print, e.g., '1-5, 8, 11-13'. Defaults to the empty string, which means print all pages.
**Paper** rang**es** should be replaced by Pages range

**Comment by 9520prashant** [comment]
Can I work on it?

**Comment by dsanders11** [comment]
> Hum Sound strange for the margins to be set in inches and said default to cm.... margin in inches. Defaults to 1cm (~0.4 inches).

This is indeed a little strange, but that's how the API is set up, so I believe the documentation is accurate.

> Paper ranges should be replaced by Pages range

Thanks! I've opened https://github.com/electron/electron/pull/39378 upstream to fix this in the docs. In the future please make an issues regarding docs mistakes on https://github.com/electron/electron so they can be addressed more promptly. 👍
