### ISSUE TITLE
Block display error while rendering markdown

### ISSUE THREAD

**Issue by fr1g** [electron/website#312]
https://www.electronjs.org/zh/docs/latest/tutorial/tutorial-preload
here appears:
![image](https://user-images.githubusercontent.com/53085628/204143025-0019645b-15da-448f-afd1-a08206dfb894.png)

which is expected like 
![image](https://user-images.githubusercontent.com/53085628/204143041-0f63d79a-56ce-41eb-9a65-3b82db6ba645.png)
block.

perhaps there cannot include a form?

**Comment by erickzhao** [comment]
@fr1g I believe the issue is because there's an extra space between `:::` and `info`.

```
::: info
This won't work ❌
:::
```

```
:::info
This will work ✅
:::
```
