### ISSUE TITLE
can't find pages

### ISSUE THREAD

**Issue by wkxs** [electron/website#313]
can't find “packaging your application” and “publish and updating” page

**Comment by albu77** [comment]
This could help ?
![image](https://user-images.githubusercontent.com/624802/204341295-a6a35bbe-ba79-45ad-b205-e924db9e73c8.png)

**Comment by erickzhao** [comment]
@wkxs the tutorial ones?

https://www.electronjs.org/docs/latest/tutorial/tutorial-packaging
https://www.electronjs.org/docs/latest/tutorial/tutorial-publishing-updating

**Comment by wkxs** [comment]
amazing!,it works,thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Alain ***@***.***&gt;; 
发送时间: 2022年11月29日(星期二) 凌晨1:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [electron/website] can&#39;t find pages (Issue #313)





 
This could help ?
