### ISSUE TITLE
Theme toggle contrast issue in when in light mode

### ISSUE THREAD

**Issue by dewanshDT** [electron/website#354]
## current behavior on hover
![electron](https://user-images.githubusercontent.com/71703033/214946897-9ff19f84-ac06-4fcc-94bf-fdaf99a5b0b6.png)

## expected behavior on hover
![electroncorrect](https://user-images.githubusercontent.com/71703033/214946847-aed1c79d-8875-4850-b13f-290c4a46a8d8.png)

### this is a design flaw and improving this will make the website more accessible and visible to a wider range of users.

@erickzhao I would like to fix this please assign this to me.

**Comment by erickzhao** [comment]
I can reproduce this on a stock Docusaurus website as well. It's not related to any styling issues on our end. Maybe you want to fix this upstream instead?

https://github.com/facebook/docusaurus

**Comment by dewanshDT** [comment]
okay

**Comment by santosh-kuchetti** [comment]
I am getting an error as 
'docusaurus' is not recognized as an internal or external command,
operable program or batch file.

when npm add docusaurus --dev, then alsoit is adding. what i need to do for this.

**Comment by erickzhao** [comment]
> what i need to do for this.

To install the Electron website locally? You should just need to install the dependencies that are already listed. We use Yarn Classic for local dev, so you would want to do `yarn` and then `yarn start` to run the website in dev mode.

If you want to start a new Docusaurus website, you should follow their Getting Started guide:
https://docusaurus.io/

I don't believe they use the `docusaurus` package at all for V2.

**Comment by santosh-kuchetti** [comment]
I could not find out the element using dev tools. How can we know where the elements are present in the code base using dev tools? I tried to find the elements based on the class names which are in the dev tools. But i could not find out. This is very interesting. i would love to know how to find the elements in the codebase

**Comment by dewanshDT** [comment]
Actually you don't need to do anything in this issue. This issue is not present in electron website it is problem of docusaurus itself and I've already reported it.

**Comment by erickzhao** [comment]
Thanks @dewanshDT. I'll close this out!
