### ISSUE TITLE
Navbar carets should never appear on a separate line

### ISSUE THREAD

**Issue by JrDevHarsh** [electron/website#369]
The items in the navbar menu are not properly aligned center when transitioning from the `mobile` to the `desktop` screen. Here is the screenshot of the bug:

![issue](https://user-images.githubusercontent.com/94737463/217163265-4368f90b-ecf3-4df6-86b9-c67c35c03e0b.png)

**Comment by JunDevHarsh** [comment]
Can I work on this issue?

**Comment by erickzhao** [comment]
Sure thing

**Comment by santosh-kuchetti** [comment]
I would love to contribute to this repo. Could you please assign this issue to me..?

**Comment by santosh-kuchetti** [comment]
Are we having any channel so that we can discuss our doughts..?

**Comment by JunDevHarsh** [comment]
@santosh-kuchetti You can work on this issue if you want to

**Comment by santosh-kuchetti** [comment]
Sure, thanks. Can i know our community channels so that i can disacuss my doughts there

**Comment by santosh-kuchetti** [comment]
the class names that are available in the developer tools are not even available in the code base. It is really hard to find them in the code base.  can you please help me with this @erickzhao?

**Comment by prachiMeshram** [comment]
@erickzhao, I have fixed this issue in my system and created a PR.
Can you please review it and accept the PR

**Comment by prachiMeshram** [comment]
@erickzhao can you please review my PR now

**Comment by hansupadhyay007** [comment]
Hey there..
I really wanted to work on this issue. Could you please assign me this...

**Comment by MoazMirza-13** [comment]
fixed this issue in https://github.com/electron/website/pull/460

**Comment by MoazMirza-13** [comment]
@erickzhao i need someone to review my pr to be merged.

**Comment by MoazMirza-13** [comment]
hey @erikian can you tell me what should i do now ? should i wait for someone to review it ?
and in my notifications i am also seeing that an error occured "check semantic commit", what should i do about it ?

**Comment by Sankalp2114** [comment]
hey i have fixed this issue can you please review it @erickzhao (#530)
