### ISSUE TITLE
Outdated timeline on electronjs.org

### ISSUE THREAD

**Issue by marcwrobel** [electron/website#374]
According to https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline, 20.0.0 is still supported. But according to https://www.electronjs.org/blog/electron-23-0#end-of-support-for-20xy Electron 20.x.y is EOL.

It seems https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline is not up-to-date.

**Comment by anj20** [comment]
@marcwrobel is this issue open now?

**Comment by marcwrobel** [comment]
@anj20, looks like the page was updated since I opened this issue. Closing it.
