### ISSUE TITLE
Example doesn't work in "Tutorial: Using Preload Scripts"

### ISSUE THREAD

**Issue by unfode** [electron/website#391]
I set up [my project](https://github.com/unfode/my-electron-app) according to the "Using Preload Scripts" [tutorial](https://www.electronjs.org/docs/latest/tutorial/tutorial-preload). But it doesn't print out "pong" as expected.

Expected behavior:

![image](https://user-images.githubusercontent.com/95689995/226982702-baa8d4d0-3b96-4852-a1bf-ce7a46f49379.png)

Actual behavior:

![image](https://user-images.githubusercontent.com/95689995/226983051-6d01dbe6-04fe-4eab-970a-05ea1c2cb1c9.png)

Versions and Platform
- OS: macOS Ventura 13.2.21
- Node version: v16.17.0
- Electron version: 23.1.3

**Comment by dsanders11** [comment]
@unfode, I'm going to close this as it's the wrong repo, and also because I believe it is working as expected.

The "pong" is logged using `console.log` in the renderer process - if you open dev tools in the renderer, you should see it there. It is not logged to the terminal.
