### ISSUE TITLE
[Doc]: Wrong way to use electron-forge by yarn

### ISSUE THREAD

**Issue by 0xf9527** [electron/website#420]
![image](https://github.com/electron/website/assets/106571326/7cf6c7af-a8c8-499d-9e04-9a7333d40b99)

https://www.electronjs.org/docs/latest/tutorial/quick-start#package-and-distribute-your-application

It would be `yarn electron-forge import`

**Comment by erickzhao** [comment]
I think we could write a custom converter or upstream this issue to the Docusaurus repo as a step forward.

Thanks for the report @0xf9527 !

**Comment by erickzhao** [comment]
Looks like this is a wontfix and we should be running `npx` here according to the linked Docusaurus issue.
