### ISSUE TITLE
Timeout issue when start website

### ISSUE THREAD

**Issue by KostadinGorgiev** [electron/website#440]
I'm getting timeout issue when try npm start

...
[ERROR] Error: Timed out waiting for API structure content from /docs/latest/api/structures/keyboard-event.md
[ERROR] Error: Timed out waiting for API structure content from /docs/latest/api/structures/resolved-host.md
...

How can I fix this issue?

**Comment by dsanders11** [comment]
Are you running it on Windows by chance?

**Comment by KostadinGorgiev** [comment]
Yes, I'm running on windows 11

**Comment by dsanders11** [comment]
It is likely an issue with Windows file paths in some of the recent code changes.

Unfortunately Windows is not really a supported platform for this repo. We don't test it on CI or develop locally on it, so it's not a priority to ensure it runs there.

PRs welcome to improve Windows support in the codebase, but I have a feeling this error is just one of several that you'd run into running this repo on Windows.

**Comment by dsanders11** [comment]
Closing this now as not planned since Windows isn't really supported.

**Comment by vishal-3205** [comment]
@KostadinGorgiev - I tried on Win 10 and Win 11 using WSL + Node 20 + Yarn and it worked like a breeze. 

Hope it helps anyone using Windows OS and wants to run this code.
