### ISSUE TITLE
windows jsfiddle downloads broken with 0.34.3

### ISSUE THREAD

**Issue by brett-koonce** [electron/website#452]
1) user on windows visits site:
> https://www.electronjs.org/fiddle
2) user clicks download button for windows
3) URL 404's --> no files to download

possible solutions:
* upload windows binaries
* redirect to 0.34.2 for now

**Comment by brett-koonce** [comment]
+ mac intel/arm builds as well

**Comment by dsanders11** [comment]
Fixed by #455.
