### ISSUE TITLE
[enhancement] : add pagination to https://www.electronjs.org/apps

### ISSUE THREAD

**Issue by tabishnaqvi1311** [electron/website#453]
### Description
The current showcase page  [https://www.electronjs.org/apps](https://www.electronjs.org/apps) on the project's website lacks pagination. Users are currently required to scroll through a large list of apps, which leads to poor user experience.

### Expected behaviour
Provide navigation controls such as page numbers, "Next" and "Previous" buttons, or a "Load More" button to allow users to browse through multiple pages of showcased items.

### What will this achieve?
Improved UX and faster page loading times

**Comment by UtkarshAhuja2003** [comment]
Hii @tabishnaqvi1311 
I would like to contribute to this issue. Can you please assign it to me?

**Comment by tabishnaqvi1311** [comment]
Hey, I'm no maintainer, but if possible would like to collaborate on this with you!

**Comment by UtkarshAhuja2003** [comment]
That sounds great. I'd be happy to collaborate with you.

**Comment by tabishnaqvi1311** [comment]
Sure, my discord username is naqvi1311
