### ISSUE TITLE
Upgrade to Docusaurus v3

### ISSUE THREAD

**Issue by erickzhao** [electron/website#466]
Docusaurus just released a new major version!

https://docusaurus.io/blog/preparing-your-site-for-docusaurus-v3

TODO: flesh this out into smaller issues before we do the major version upgrade.

**Comment by rayyan21d** [comment]
hey eric Docusaurus 3.1 is out. What's to be done next in order to perform the major version upgrade?

**Comment by AnjaliChoudhary99** [comment]
Hey @erickzhao 

I'm willing to contribute to the upgradation process.
I'm new to this and would like to learn by contributing.

Can you let me know what version of Docusaurus we are using?

**Comment by thilak007** [comment]
@erickzhao , The `electronjs` package is currently using  `react@17.0.2` . Upgrading to Docusaurus v3 requires `React v18.0+` as per the [documentation](https://docusaurus.io/docs/migration/v3#upgrading-dependencies) . Are we planning to upgrade to React v18 soon?
