### ISSUE TITLE
Update Website Copyright to 2024

### ISSUE THREAD

**Issue by amanr-dev** [electron/website#509]
The copyright year on the Footer is outdated and it needs to be updated.

**Comment by Aaqilyousuf** [comment]
i would like to work on this issue can you assign it to me

**Comment by Aaqilyousuf** [comment]
hey i updated the copyright year, i cant make a PR it show 
Review required
At least 1 approving review is required by reviewers with write access

**Comment by amanr-dev** [comment]
Assigned to @Aaqilyousuf

**Comment by amanr-dev** [comment]
> hey i updated the copyright year, i cant make a PR it show Review required At least 1 approving review is required by reviewers with write access

Hi @Aaqilyousuf, I was referring to the Footer's copyright. Can you also change it to 2024?

![Screenshot 2024-02-19 195149](https://github.com/electron/website/assets/124811276/ab8ee8ae-5339-4a71-89c2-ba4830bd1d65)
