### ISSUE TITLE
[BUG]: Electron logo icon briefly disappears and reappears during theme change

### ISSUE THREAD

**Issue by CezarDrumea** [electron/website#539]
### Brief Summary
When users click the theme change icon, the Electron logo icon momentarily disappears and then quickly reappears. This flickering effect occurs every time a theme change is initiated.

### Steps to Reproduce
1. Launch the application.
2. Locate the theme change icon.
3. Click on the theme change icon to initiate a switch between dark mode and light mode.
4. Carefully observe the area where the Electron logo is displayed during the theme transition.

### Expected Behavior
Transitioning between themes should only alter theme-specific attributes (colors, fonts, etc.) without causing the logo to flicker.

### Actual Behavior
Upon initiating a theme change via the theme switcher icon, the Electron logo icon quickly disappears and then reappears, creating a noticeable flicker.

### Screenshots
![Screenshot 2024-03-24 191102](https://github.com/electron/website/assets/109078443/355d6828-20e9-4b00-93de-eb6f6b3e5ec3)
![Screenshot 2024-03-24 191030](https://github.com/electron/website/assets/109078443/a88902a2-c59f-4a28-96a8-57770e2a702b)

**Comment by JasonFengGit** [comment]
Hi @erickzhao, I compared Electron website with Docusaurus.io, the logo on Docusaurus.io also has a blinking effect when changing dark/light themes, but the position of its title does not move. The key difference I found is that Electron website does not specify the height and width of the logo. 
![image](https://github.com/electron/website/assets/40121574/77a1f68f-d39e-46e4-aa85-ededef612e49)

We should be able to achieve the same result by adding height and width specification in docusaurus.config.ts

![image](https://github.com/electron/website/assets/40121574/0017a80d-250d-4112-aab2-33d24bc0d989)

**Comment by JasonFengGit** [comment]
There are some previous discussions here: https://github.com/facebook/docusaurus/issues/8188

**Comment by JasonFengGit** [comment]
Hi @erickzhao, may I get some inputs from you about this issue?

**Comment by JasonFengGit** [comment]
Hi @erickzhao, found a workaround and drafted a PR https://github.com/electron/website/pull/543.

Built and tested on my local environment (windows, chrome) with different window sizes.

**Comment by JasonFengGit** [comment]
PR https://github.com/electron/website/pull/543 ready
