### ISSUE TITLE
Replace @docusaurus/plugin-google-analytics Plugin

### ISSUE THREAD

**Issue by dsanders11** [electron/website#581]
[According to the docs, this plugin is deprecated and stopped working in July 2023.](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-analytics)

cc @erickzhao 

https://github.com/electron/website/blob/f2a1e452ba3d4cbd0d26e4e9b9dcb948b81dd83f/package.json#L34

**Comment by Vishesh-Paliwal** [comment]
Hey @dsanders11 , Can you assign this issue to me , I would love to work on it .

**Comment by dsanders11** [comment]
@Vishesh-Paliwal, we don't assign issues to outside contributors. Feel free to send a PR. 🙂

**Comment by Vishesh-Paliwal** [comment]
Sure @dsanders11 , Thanks for early response . Will raise a PR soon :+1:

**Comment by Vishesh-Paliwal** [comment]
@dsanders11 , Kindly review  . replaced it with with [@docusaurus/plugin-google-gtag](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-gtag)
