### ISSUE TITLE
Separate i18n build per language

### ISSUE THREAD

**Issue by erickzhao** [electron/website#631]

**Comment by harshal050** [comment]
[i18n.zip](https://github.com/user-attachments/files/17612422/i18n.zip)
harshal050/issue#631

I attach this i18n file for the French and Dutch languages. If you need more languages, please let me know. I can also create the i18n for specific languages. This is my first contribution, and I hope you enjoy my work!

**Comment by erickzhao** [comment]
As a paper trail, I looked into this yesterday and it seems like this would be more work than it's worth. For reference, the `--locale` flag for the `docusaurus build` command is designed specifically for a multi-site deployment (see https://docusaurus.io/docs/i18n/tutorial#multi-domain-deployment) and doesn't generate the appropriate `/lang` URL paths out of the box.

I don't think the brittleness added by hacking around link formatting is worth it to save on build time and parallelization of the i18n builds.
