### ISSUE TITLE
Module names shouldn't be translated

### ISSUE THREAD

**Issue by nikwen** [electron/website#635]
In the German translation, lots of module names are getting translated:

- [BrowserWindow](https://www.electronjs.org/de/docs/latest/api/browser-window) -> Browserfenster
- [Menu](https://www.electronjs.org/de/docs/latest/api/menu) -> Menü
- [Notification](https://www.electronjs.org/de/docs/latest/api/notification) -> Mitteilung
- [Tray](https://www.electronjs.org/de/docs/latest/api/tray) -> Fach

It's confusing to find a name in your code, search for it on the website and then not find it because it was translated.

![Screenshot](https://github.com/user-attachments/assets/cac497f4-b095-4520-9528-3576ab1cabb4)

**Comment by erickzhao** [comment]
Hey @nikwen, thanks for flagging this. I've fixed these instances by [deleting the translations on Crowdin](https://crowdin.com/editor/electron/258377/en-de?view=comfortable&filter=basic&value=0#q=tray). The next deploy should pick those changes up. If you spot any more problems, feel free to submit amended (non-?)translations as well!

**Comment by nikwen** [comment]
Thank you, @erickzhao!
