### ISSUE TITLE
Copyright year wrong in footer

### ISSUE THREAD

**Issue by nikwen** [electron/website#636]
At the time of writing, the copyright is listed as 2023 on [electronjs.org](https://www.electronjs.org/):

![Screenshot](https://github.com/user-attachments/assets/30a0afc6-9ce1-4aac-8ed5-6ccde99fd724)

**Comment by MarshallOfSound** [comment]
This is a common misconception in how copyright declarations work, the year does not need to be kept up to date. This is current guidance from OpenJS as well as of the last time we had this discussion

**Comment by nikwen** [comment]
Thanks for your quick reply! I think of it more like this:

When I go to a project website and there is a copyright year and the copyright year is outdated, I assume the project is dead or not actively maintained or the maintainers do not care enough about the project to take care of details like this. Then I often don't use those projects.

With Electron this is obviously not the case. Maintainers do care and it's actively maintained. However, from the website I might get a different impression.

If you don't plan on updating the year, why not remove it at all? Then it won't seem like maintainers don't care to update it.
