### ISSUE TITLE
Incorrect rendering of embedded API structure hover cards

### ISSUE THREAD

**Issue by erickzhao** [electron/website#682]
![Image](https://github.com/user-attachments/assets/63da8ecc-06b2-47cb-9fb6-d16c5460697f)

**Comment by kaushik7kk** [comment]
Hello, @erickzhao ! I'm kinda new to Electron. Could you let me know how the hover cards are actually supposed to be rendered and if any extra input on the same will be further required?

**Comment by erickzhao** [comment]
Hi @kaushik7kk,

For example, see what the `Point` object is supposed to look like: https://www.electronjs.org/docs/latest/api/structures/point

For some reason, the document title is being rendered with a `<header></header>` portion and we apparently can't render it using the `react-markdown` library.

The component that we use to render this text is located here: https://github.com/electron/website/blob/main/src/components/APIStructurePreview.tsx

**Comment by erickzhao** [comment]
@kaushik7kk unfortunately it looks like I solved this one as part of a PR solving an unrelated bug. Thanks for writing in to ask about the issue, though!

**Comment by kaushik7kk** [comment]
Thanks for informing me @erickzhao . I'll catch up with the PR to get some more info on what fixed it.

**Comment by dsanders11** [comment]
Looks like one of the Docusaurus updates changed the rendering of the title there from to be wrapped in a `<header></header>`. I believe we could fix it by adding `header` to this list of allowed elements, or it will be fixed once #690 is merged.

https://github.com/electron/website/blob/fc2c6b5e9827e56682cb2c0994612b447757f6f9/src/components/APIStructurePreview.tsx#L107
