### ISSUE TITLE
Outdated docs on the website

### ISSUE THREAD

**Issue by nikwen** [electron/website#689]
The following section is missing from the [website version](https://www.electronjs.org/docs/latest/api/base-window):

https://github.com/electron/electron/blob/f595443a22a01b61750942532cbf38bef12626f3/docs/api/base-window.md#resource-management

**Comment by erickzhao** [comment]
Seems like we need to backport https://github.com/electron/electron/commit/72802c374b8fa719fbd2ec69cf25079a3db67df3 to `33-x-y` :)

**Comment by erickzhao** [comment]
Opened https://github.com/electron/electron/pull/44874

**Comment by nikwen** [comment]
Thanks for explaining, @erickzhao! I didn't know docs PRs needed to be backported.

Is there a way to have trop do it or do I have to do it manually?

This will also be relevant for all future PRs of mine that someone merges without applying proper backport tags. (Unfortunately, I can't apply them myself.)

**Comment by nikwen** [comment]
Thanks again for explaining and for the backport! I also backported another PR to 33 to make it show up on the website: https://github.com/electron/electron/pull/44875

I'll keep this in mind going forward and check that my docs PRs are backported properly.

**Comment by erickzhao** [comment]
> Is there a way to have trop do it or do I have to do it manually?

@nikwen Unfortunately, the best way would be to ping a maintainer or do it manually. Without the ability to add labels or run trop manually.

The `[e backport](https://github.com/electron/build-tools?tab=readme-ov-file#e-backport-pr)` command in Electron Build Tools makes this task slightly easier as well.

**Comment by nikwen** [comment]
Thanks! I didn't know about `e backport`. Will check it out.

If I ping a maintainer, can they run Trop to do a backport of a PR that has already been merged? Or would I just be putting the burden on them to do a manual backport?
