### ISSUE TITLE
Apps section

### ISSUE THREAD

**Issue by molant** [electron/website#74]
We need to make the content of https://www.electronjs.org/apps available in Docusaurus.

In the current site the pages are generated dynamically based on data stored on a (quite large) JSON file. Instead of generating those pages dynamically we could create a static page for each one, maybe as part of the (pre)build step so we don't have to send MB of JSON over the wire.

**Comment by subashpaul** [comment]
i would like to work on this project.

**Comment by subashpaul** [comment]
Please explain me the details of the work.
