### ISSUE TITLE
Docs don't get updated when there is a new major version

### ISSUE THREAD

**Issue by molant** [electron/website#91]
It looks like we are not receiving the payload as v14 was released yesterday and the latest notification is from 5 days ago:

![image](https://user-images.githubusercontent.com/606594/131537837-6ad74897-2cf4-407b-80b6-21c2f9765c63.png)

Need to figure out if electron-updater is not getting the right payload or it is not sending it.

**Comment by erickzhao** [comment]
I think this is resolved. Haven't had to deal with manual major version bumps in a while.
